services:
  # tundrabot:
  #   build:
  #     context: .
  #   image: tundrabot:latest
  #   container_name: tundrabot
  #   restart: unless-stopped
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   environment:
  #     MONGOOSE_PROTOCOL: mongodb
  #     MONGOOSE_URL: mongodb
  #     MONGOOSE_USERNAME: root
  #     MONGOOSE_PASSWORD: example
  #   networks:
  #     - tundrabot-network
  #   ports:
  #     - ${DASHBOARD_PORT}:${DASHBOARD_PORT}
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - tundrabot-network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
networks:
  tundrabot-network:
    driver: bridge
volumes:
  pgdata: