on:
  push:

jobs:
  define-matrix:
    runs-on: ubuntu-24.04
    outputs:
      node-versions: ${{ steps.node-versions.outputs.node-versions }}
    steps:
      - name: Define Node.js versions
        id: node-versions
        run: |
          echo 'node-versions=["22.12.0", "latest"]' >> "$GITHUB_OUTPUT"

  lint:
    runs-on: ubuntu-24.04
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(needs.define-matrix.outputs.node-versions )}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up dependencies
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: 10
      - name: Run ESLint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-24.04
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(needs.define-matrix.outputs.node-versions )}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up dependencies
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: 10
      - name: Run tsc to typecheck
        run: pnpm typecheck
